export const UPDATE_INPUT = 'UPDATE_INPUT';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const CONVERT_INPUT = 'CONVERT_INPUT';
export const CONVERT_INPUT_FAILURE = 'CONVERT_INPUT_FAILURE';
export const CONVERT_INPUT_SUCCESS = 'CONVERT_INPUT_SUCCESS';
export const CONVERT_RESET = 'CONVERT_RESET';
